### ISSUE TITLE
Idea: Sort function for two Moment instances

### ISSUE THREAD

**Issue by franzliedke** [pk4media/ember-cli-moment-transform#1]
It happens quite often that we want to sort objects by date in our controllers. We need to provide a sorting callback to the Array#sort method.

This is such a common use-case; could this package support it?

If yes, it should take into account cases when a date is `null` and not a valid Moment instance.

**Comment by franzliedke** [comment]
The helper could look something like this:

``` javascript
function compare(obj, f1, f2) {
    var date1 = obj.get(f1);
    var date2 = obj.get(f2);

    if (!moment.isMoment(date1)) {
        return -1;
    } else if (!moment.isMoment(date2)) {
        return 1;
    }

    if (date1.isBefore(date2)) {
        return -1;
    } else if (date1.isAfter(date2)) {
        return 1;
    }

    return 0;
}
```

**Comment by dnegstad** [comment]
Sorry, just saw this issue now.

The moment objects exposed by this plugin are actually updated for Ember.Comparable and have been extended with an Array.sort compatible compare method. jasonmit/ember-cli-moment-shim#3 is the relevant pull request.

Hopefully that does the trick for you.

**Comment by franzliedke** [comment]
Cool! How exactly do I use that?

**Comment by dnegstad** [comment]
If you're trying to sort an array of records by a common date time field, Ember.Comparable makes it really easy with the [Ember.computed.sort](http://emberjs.com/api/classes/Ember.computed.html#method_sort) method. The Ember.Comparable implementation from that pull request means it'll just work.

In your class, you define one property for your sort options and another to do the actual sorting:

``` javascript
sortProperties: ['mydate:asc'],
sorted: Ember.computed.sort('name of your collection', sortProperties)
```

If you just need to sort an array of moment objects, you can call .sort on the array as .sort(moment.compare) to use the comparable method for sorting directly.

**Comment by dnegstad** [comment]
@franziledke Did you get sorting working?

**Comment by franzliedke** [comment]
Yep, implemented it two days ago. Thanks for helping me along.

**Comment by Rio517** [comment]
For anyone else stumbling across this, note that `sortedProperties` need to be passed in as a string.

``` js
sortProperties: ['mydate:asc'],
sorted: Ember.computed.sort('name of your collection', 'sortProperties')
```

**Comment by franzliedke** [comment]
Further note: Since `ember-cli-moment-shim` version 3.0+, this no longer works: https://github.com/jasonmit/ember-cli-moment-shim/issues/97
